### ISSUE TITLE
Add diagram for pv-site-datamodel

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#100]
It would be great to a datamodel diagram of how the different tables link together. Think I think can be done with a `mermaid` diagram. The links with the tables are defined by foreign relations in https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/sqlmodels.py

**Comment by bikramb98** [comment]
Happy to take on this one! I've worked with PlantUML before, and will be interesting to learn mermaid

**Comment by bikramb98** [comment]
@peterdudfield I tried looking for tools that can auto-generate schemas, but they require access to the database. I did the schema diagram using mermaid and I've put it on the repo level `README.md`. Another place it can go is as a new `README.md` in folder `pvsite_datamodel`. Let me know if you want me to move the diagram!

**Comment by peterdudfield** [comment]
Thank you very much @bikramb98
