### ISSUE TITLE
Write api request

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#112]
## Detailed Description
It would be good to have a function that takes in the API request and user, and saves to the databsae

## Context
- good for database to store all API requests

## Possible Implementation
very similar to this function https://github.com/openclimatefix/uk-pv-national-gsp-api/blob/main/src/database.py#L387, but using this datamodel
- add tests to check it has been writen

**Comment by suleman1412** [comment]
Hi Peter, can I get assigned to this issue?

**Comment by suleman1412** [comment]
hey @peterdudfield I have made the changes, Could you please take a look and let me know if everything looks okay to you?
