### ISSUE TITLE
Create an edit_site function

### ISSUE THREAD

**Issue by Bvr4** [openclimatefix/pv-site-datamodel#144]
## Detailed Description
Create a function to edit site metadata

## Context
This function will be useful to the pv-site-api, specially for the [issue 178 : edit site](https://github.com/openclimatefix/pv-site-api/issues/178) 

## Possible Implementation
here : https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/write/user_and_site.py

**Comment by Bvr4** [comment]
I'd like to be assigned to this issue as I am working on the pv-site-api side of this issue.

Should this function update all fields, or only those that are filled in? (ignoring those set to None)

**Comment by peterdudfield** [comment]
I think we should update all the fields even if None. An odd edge case is, we might want to se some fields back to None. Do you think that'll work?

**Comment by Bvr4** [comment]
I hadn't thought of this edge case. It's easier to update all the fields whatever.

However, we need to make sure that the user reads the site values before updating them, so that he knows the current values of all the fields.

**Comment by Bvr4** [comment]
Something like a pydantic PVSiteEditMetadata model, with all fields set to Optional ?

**Comment by peterdudfield** [comment]
yea soudn about right. Does PVSiteEditMetadata site here on in the api?

**Comment by Bvr4** [comment]
In my opinion, as PVSiteEditMetadata will be used here and in the API, it should be defined here, and imported in the API.

But looking at how the existing "create_site" part is handled, the API has a pydantic model defined, but the create_site part in pv_site_datamodel has no pydantic model as input, only parameters. Which may seem a bit odd.

Sorry, these may be details, but I don't want to mess up the code base, and stay consistent with it.

**Comment by peterdudfield** [comment]
yea sure, no worries. This could just be how the code base was built up. 

I would be tempted to try moving PVSiteEditMetadata here, and building the function around that.
