### ISSUE TITLE
Client table

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#148]
## Detailed Description
it would be nice to have a client table, which is joined to the sites table

## Context
- nice to know which sites belong to which client
- we could make a n by n join with users too, but perhaps this could be in a later issue

## Possible Implementation
- add client table with, client_name
- join with sites table
- make migration

**Comment by Bvr4** [comment]
Hello, I'd like to work on this issue. Can it be assigned to me ?

Do you want other fields than client_name ?

I assume that we'll need to create crud operations to this table, and maybe an edit_site_client function ?

**Comment by peterdudfield** [comment]
yea your are right @Bvr4, we used to have it, and then switched to user and sites. 

We would like it back, and yes, making it nullable would be great, and then much easier to role out

**Comment by peterdudfield** [comment]
It would be great to have a few functions
- create_client
- read_client from client_name, i like the option to create the client if it doesnt exist
- edit_client
- assign_site_to_client, this will make it easy to assign sites to certain client names

Feel free to split these up into different issues/ PRs if you want too, no pressure

**Comment by Bvr4** [comment]
OK, I was working on create_client and edit_client function today. I put them in write/user_and_site.py. But I wonder if it would be better in another file, like write/client.py ?

**Comment by peterdudfield** [comment]
Thanks so much for this @Bvr4 . Yea I would go for a different file

**Comment by peterdudfield** [comment]
Thanks for you work on this @Bvr4 . 

Would you like to do the extention on this, this would be to add an optional 0-n join with users aswell? 
Also a assign_user_to_client too?

**Comment by Bvr4** [comment]
Yes, with pleasure

**Comment by peterdudfield** [comment]
> Yes, with pleasure

Thank you. Its probably worth doing user_site_groups too as an optional 0-n join with client, as well as an assign function. I think this would then cover all cases

**Comment by Bvr4** [comment]
Just to be sure, a client can be related with multiple users. Can a user be related with more than one client ?

**Comment by peterdudfield** [comment]
> Just to be sure, a client can be related with multiple users. Can a user be related with more than one client ?

Possibly, like OCF users, but perhaps could we could start with a user can only be part of one client, and then we can add to it, if we need it

**Comment by peterdudfield** [comment]
Thanks @Bvr4 for making an issue, perhaps Ill code this one, if thats ok with you?

**Comment by Bvr4** [comment]
Yes if you prefer
