### ISSUE TITLE
get site group if it exists

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#153]
## Detailed Description
Currrently when making a new user, if it doesnt exsits, a new user and site group is made.
Sometimes the site group already exists, so we should laod that, not cause an error by overwriting it

## Context
- good to reduce errors

## Possible Implementation
in the code [here](https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/read/user.py#L29), try to get a site group with this email first, and if it doesnt exsits, then make it. 
it would also be nice to use [create_site_group](https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/write/user_and_site.py#L47) function to reduce code

**Comment by ProfessionalCaddie** [comment]
Hello. Would you please assign this to me? I am trying to build my open source contributions!

**Comment by peterdudfield** [comment]
Of course, thanks @ProfessionalCaddie

**Comment by ProfessionalCaddie** [comment]
Hello @peterdudfield ,
I have learned a lot so far and I think I have a good test and solid logic but I am having trouble running tests. 

I am assuming the issue is with poetry as I have had trouble installing certain packages inside the virtual environment(greenlet,numpy). So I started from the forked version(no changes)and changed Poetry's dependencies to be all the latest versions. 

Now I can run the pytest command but it fails the tests/test_alembic.py.  Do you have any way to move forward?

**Comment by peterdudfield** [comment]
whats the error you get?

**Comment by ProfessionalCaddie** [comment]
FAILED tests/test_alembic.py::test_migrations - docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')

Is this because I haven't started a local database in docker?

**Comment by peterdudfield** [comment]
you have to start up the docker engine locally. I do this by starting the docker desktop app

**Comment by peterdudfield** [comment]
what structure do you propose?

I dont quite understand the circular import, but perhaps havent look at the code enough?

**Comment by peterdudfield** [comment]
Ah I see. Try to do what make sense and then we can review. I do like the separation of read and write at the moment. 

And note, api is one component that uses this, but there are a few other components that use this too. So I'd probably be against a pure api file.

**Comment by ProfessionalCaddie** [comment]
Hi Peter. 

I added a pull request but I wasn't sure how to have it show in this issue. Here is the link: https://github.com/openclimatefix/pv-site-datamodel/pull/154

**Comment by peterdudfield** [comment]
The next step would be to use this new version in https://github.com/openclimatefix/india-api and https://github.com/openclimatefix/pv-site-api

**Comment by ProfessionalCaddie** [comment]
@peterdudfield, does this mean to follow steps in readme for one or both of those projects and run tests? Does this entail anything else?

**Comment by peterdudfield** [comment]
For India-api, it should be just increase the version here https://github.com/openclimatefix/india-api/blob/main/pyproject.toml#L22

For pv-site-api, increase the version [here](https://github.com/openclimatefix/pv-site-api/blob/main/pyproject.toml#L23) and also update the poetry lock file

**Comment by ProfessionalCaddie** [comment]
hi @peterdudfield. I think I did what's required, I changed the files and then created new pull requests. Please let me know if anything else has to be done. Thanks

**Comment by peterdudfield** [comment]
Thanks @ProfessionalCaddie ill close this now

**Comment by peterdudfield** [comment]
@all-contributors please add @ProfessionalCaddie  for code

**Comment by ProfessionalCaddie** [comment]
@peterdudfield Thanks!
