### ISSUE TITLE
Add GenerationSQL unique

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#26]
Add unique constrains on `site_uuid` and `datetime_interval_uuid`

**Comment by devsjc** [comment]
Do you mean the combination of the two should be unique in the generation table?

**Comment by peterdudfield** [comment]
yep, that makes sense right?

**Comment by peterdudfield** [comment]
Did we do this @devsjc ?

**Comment by peterdudfield** [comment]
maybe @simlmx did this?

**Comment by simlmx** [comment]
We have this that might be equivalent:
https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/sqlmodels.py#L95
