### ISSUE TITLE
Make first alembic migration

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#4]
## Detailed Description
`Alembic` covers migrations nicely from sqlalmcy. The task here is to make the first migrations which creates the tables and relationships

https://alembic.sqlalchemy.org/en/latest/

## Possible Implementation
See code in [here](https://github.com/openclimatefix/nowcasting_datamodel/tree/main/nowcasting_datamodel/migrations) 
Need to
1. add alembic.ini file
2. add small app with click commands to make it easy to run the `make-migrations` and the 'run-migrations` command

**Comment by simlmx** [comment]
Done in #51
