### ISSUE TITLE
Set up proper python dependency management

### ISSUE THREAD

**Issue by simlmx** [openclimatefix/pv-site-datamodel#49]
## Description
Currently, all the python dependencies are not listed (in particular the development ones). For instance I can see from the `pyproject.toml` that `ruff` is used to lint the code, but there is no defined dependency on `ruff`, and no instructions on how to run it.

## Recommended implementation
* Use `poetry` to manage the dependencies
* Add instructions on how to install dependencies, and how to format/lint/test the python code

**Comment by peterdudfield** [comment]
linked to #29

**Comment by simlmx** [comment]
Done in #53
