### ISSUE TITLE
Latest Forecat values

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#64]
## Detailed Description
The current API takes 1.5 minutes to get one forecast. This is too slow. 

```
SELECT *
FROM (
	SELECT DISTINCT ON (forecasts.site_uuid) forecasts.forecast_uuid, forecasts.timestamp_utc FROM forecasts 
	WHERE forecasts.site_uuid IN ('04b3d67f-af48-42f7-ac0f-9d07d4dd84f6'::uuid) 
	ORDER BY forecasts.site_uuid, forecasts.timestamp_utc DESC) 
	AS anon_1 
	JOIN forecast_values ON anon_1.forecast_uuid = forecast_values.forecast_uuid 
ORDER BY anon_1.timestamp_utc, forecast_values.start_utc
```

## Context
- The UI needs to be able to get 1000's of forecasts

## Possible Implementation

1. 
- Create forecast_value_latest table. This table will only save the latest forecast (forecast_horizon 0) and the latest one in the future
- Change the save functions to also save / update to this table
- Change the read function to load from this table
- This is how we do it in the `nowcasting` project

2. Add a forecast_value_forecast_hoirzon_0 table, This table will only save the latest forecast (forecast_horizon 0) 
- update save method to also save to this table
- update read method to read from this table

**Comment by peterdudfield** [comment]
Sorry if i missed anything @simlmx, i might have

**Comment by peterdudfield** [comment]
Note that getting history is easy with, so we just worried about getting the forecast values from now on
```
SELECT DISTINCT ON (forecast_values.start_utc) * from forecasts
JOIN forecast_values ON forecasts.forecast_uuid = forecast_values.forecast_uuid
WHERE forecasts.site_uuid IN ('04b3d67f-af48-42f7-ac0f-9d07d4dd84f6'::uuid)
ORDER BY forecast_values.start_utc, forecasts.timestamp_utc desc
```

**Comment by peterdudfield** [comment]
Note that the forecast value table has 100 million rows. 

If we made a latest table it would have
1000 * 96 *7  ~ 1 million rows for 7 days of data

**Comment by simlmx** [comment]
If you add `SET random_page_cost = 1.1;` before your query (the setting has not been set in the database yet, it's still pending; the `SET` command will set it temporarily), your initial query runs in 3ms.

**Comment by peterdudfield** [comment]
> If you add `SET random_page_cost = 1.1;` before your query (the setting has not been set in the database yet, it's still pending; the `SET` command will set it temporarily), your initial query runs in 3ms.

wow - amazing, ill do that right away

**Comment by peterdudfield** [comment]
I'll close this for now, as I dont think we are going to do this
