### ISSUE TITLE
add inferred metadata to site

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#65]
## Detailed Description
Would it be possible to add the inffered meta data to the site model. 

## Context
- Good to keep this in a database not in csv
- now needed for https://github.com/openclimatefix/pv-site-api/pull/55. Want to plot clear sky irradence for each site

## Possible Implementation
- add columns to sites, they can be optional
- add migrations
- run migrations
- make script to add these values (currently in csv) to the database

**Comment by simlmx** [comment]
I would vote to park this until we absolutely need it. It's quite a lot of overhead and it feels the clearsky route is doing fine without it.

**Comment by peterdudfield** [comment]
Yep, lets park for the moment, ill close it
