### ISSUE TITLE
update get_user_by_email() to not also make new users

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/pv-site-datamodel#80]
## Detailed Description
In setting up the new [site user page](https://github.com/openclimatefix/uk-analysis-dashboard/issues/39), it seems that a new user is created every time anything is entered as an email address when using the [get_user_by_email()](https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/read/user.py#L11) from the data model. 

Screenshot from the database with "new users" in rows 9, 10, 11, 12: 
<img width="922" alt="Screenshot 2023-08-29 at 08 56 55" src="https://github.com/openclimatefix/pv-site-datamodel/assets/86949265/a02b0dff-f357-4086-9921-507cc98db7d0">

Here's the `logger.info` message: 
![Screenshot 2023-08-29 at 08 55 16](https://github.com/openclimatefix/pv-site-datamodel/assets/86949265/cd0734a3-6dfe-477d-9316-ff839ac350e9)

## Context
It could be good to have  an updated read function that returns a message that could be used in the Analysis Dashboard that the user does not exist or something like that. 

## Possible Implementation
Update current `get_user_by_email` function to return message if the user is not found and data is not in the format of an email address.

**Comment by rachel-labri-tipton** [comment]
hi @peterdudfield, when you have time, I'm wondering if you could look at this issue and let me know if it might make sense to change the `get_user_email` function in the `pvsite_datamodel`.

**Comment by peterdudfield** [comment]
hmm, should the analysis dashbaord perhaps use a different function? Perhaps it doesnt need to get the email address at all?

**Comment by peterdudfield** [comment]
Ah, sorry, I'm now thinking it does need that. 

yea, can you put in a option to not make new user? Perhaps raise an error if that user doesnt exist?

**Comment by rachel-labri-tipton** [comment]
thanks! 

I think getting a list of all the emails for the moment might make the most sense and then I'll filter in the analysis dashboard. 

and i'll put an option to not make a new user on the current function. `make_new_user` already exists.

**Comment by peterdudfield** [comment]
Did this get finished?

**Comment by BraunRudolf** [comment]
Hi @peterdudfield,
I took a look, it's still open.
<details>
<summary>Code in question</summary>

```python
      def get_user_by_email(session: Session, email: str):
          """
          Get user by email. If user does not exist, make one.
      
          :param session: database session
          :param email: email of user
          :return: user object
          """
      
          user = session.query(UserSQL).filter(UserSQL.email == email).first()
      
          if user is None:
              logger.info(f"User with email {email} not found, so making one")
      
              # making a new site group
              site_group = SiteGroupSQL(site_group_name=f"site_group_for_{email}")
              session.add(site_group)
              session.commit()
      
              # make a new user
              user = UserSQL(email=email, site_group_uuid=site_group.site_group_uuid)
              session.add(user)
              session.commit()
      
          return user
```

</details>

The question is how should it be changed now?
> yea, can you put in a option to not make new user? Perhaps raise an error if that user doesnt exist?


Just a check if the email is a valid or raise an error?

**Comment by peterdudfield** [comment]
I think it would be great to add an option, "make_new_user_if_none". This could be defaulted to true. If false no user is there, then raise an error
