### ISSUE TITLE
Round to 2.d.p for kw 

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#82]
## Detailed Description
Good to keep the data small

## Context
- keeps data smaller in db

## Possible Implementation
- round the values [here](https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/write/generation.py#L52)

**Comment by assafshouval** [comment]
Maybe I'm missing something. Isn't this data is stored as float? how rounding it to 2 decimal points will make it smaller?

**Comment by peterdudfield** [comment]
> Maybe I'm missing something. Isn't this data is stored as float? how rounding it to 2 decimal points will make it smaller?

When we serve the data up in the API it gets converted to json and then more decimal places ( I think) do take up more space. Perhaps there is a different way to do this

**Comment by peterdudfield** [comment]
ive chagned it to 3.d.p places now
