### ISSUE TITLE
Update SQLAlchemy > 2.0

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#88]

**Comment by MuhammadHasnain77** [comment]
Hi,
It's my first time on Github can you guide me how to more about the issue I want to work on it.
Thanks

**Comment by peterdudfield** [comment]
Yea of course. Best to look at some documents for poetry and see how to upgrade a packageOn 2 Dec 2023 04:35, Muhammad Hasnain ***@***.***> wrote:
Hi,
It's my first time on Github can you guide me how to more about the issue I want to work on it.
Thanks

**Comment by MuhammadHasnain77** [comment]
> Yea of course. Best to look at some documents for poetry and see how to upgrade a packageOn 2 Dec 2023 04:35, Muhammad Hasnain ***@***.***> wrote:
> Hi,
> It's my first time on Github can you guide me how to more about the issue I want to work on it.
> Thanks
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Thanks I will look into it.

**Comment by peterdudfield** [comment]
Any luck @MuhammadHasnain77 ? Thanks

**Comment by roshnaeem** [comment]
Hello @peterdudfield, i opened a PR for it, as it is needed to solve https://github.com/openclimatefix/pv-site-api/issues/133

**Comment by peterdudfield** [comment]
Merged with #110
