### ISSUE TITLE
Make geopandas optional

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pv-site-datamodel#98]
## Detailed Description
Geopandas seems to come with a lot of over heads, and isnt always used, so it would be good to make it an option

## Context
- I think can be done as a poetry group
- docker file here - https://github.com/openclimatefix/india-api/actions/runs/7701047443/job/20986260353, took a long time to be built

## Possible Implementation
move geopandas dependency to seperate group

**Comment by abhijelly** [comment]
hey @peterdudfield should geopandas be moved to the dev group or a new group is needed for it? Thanks

**Comment by peterdudfield** [comment]
Dev group would be great
