### ISSUE TITLE
Pull site forecasts from SQL database 

### ISSUE THREAD

**Issue by zakwatts** [openclimatefix/pv-site-datamodel#99]
Create a script or notebook to connect to the pv site database to analyse the evolution of forecasts.

This is to do some analysis on production MAE vs backtest MAE and make sure things match up.

**Comment by peterdudfield** [comment]
This can now be done on the analysis dashbaord, did you want it for `sites` or `uk national`?

**Comment by zakwatts** [comment]
For both, I see if can be done the analysis dashboard! I'm going to close this issue :)
